name: CI/CD Pipeine

on:
  push:
    branches: [main]

jobs:
  deploy : 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker build -t diet-api .

      - name: Deploy to render
        uses: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK}}